[package]
name = "bred-api"
version = "1.0.1"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
serde_json = "1.0.79"
actix-cors = "0.6.1"
tracing = "0.1.32"
tracing-subscriber  = { version = "0.3.9", features = ["env-filter"] }
tracing-actix-web2 = "2.0.0"
fred-rs = "0.1.1"
dotenv_codegen = "0.15.0"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12.0"