[package]
name = "bred-api"
version = "1.0.2"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
serde = "1.0.137"
toml = "0.5.9"
serde_json = "1.0.81"
actix-cors = "0.6.1"
tracing = "0.1.34"
tracing-subscriber  = { version = "0.3.11", features = ["env-filter"] }
tracing-appender = "0.2.2"
tracing-actix-web2 = "2.0.0"
fred-rs = "0.1.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
scraper = "0.13.0"
