[package]
name = "bred-api"
version = "2.0.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.2.1"
actix-web-actors= "4.1.0"
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
serde_json = "1.0.85"
actix-cors = "0.6.2"
tracing = "0.1.36"
tracing-subscriber  = { version = "0.3.15", features = ["env-filter"] }
tracing-appender = "0.2.2"
tracing-actix-web2 = "2.0.0"
paris = { version = "1.5.13", features = ["macros", "timestamps", "no_logger"] }
fred-rs = "0.1.1"
reqwest = { version = "0.11.11", features = ["blocking"] }
scraper = "0.13.0"
bytestring = "1.1.0"
