[package]
name = "bred-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3.3"
serde_json = "1.0.79"
actix-cors = "0.3.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-actix-web2 = "1.0.0"