name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
          cd api && touch Config.toml
          echo fred_key = "${{ secrets.FRED_API_KEY }}" >> Cargo.toml
    - name: Build
      run: cd api && cargo build --release
    - name: Run
      run: ./target/release/bred-api
      timeout-minutes: 1
