# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Python Pip Install
        uses: logikal-code/pip-install@v1.0.0
        with:
          requirements: ./api/requirements.txt
      - name: Run Python Fetcher
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - run: python ./api/fetch.py

      # Runs a set of commands using the runners shell
      - name: rust-cargob
        uses: actions-rs/cargo@v1.0.1
        with:
        # Cargo command to run (ex. `check` or `build`)
          command: build
          # Toolchain to use (without the `+` sign, ex. `nightly`)
          toolchain: nightly
