name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create toml config file
      working-directory: api
      run: |
          touch Config.toml
          echo fred_key = '"${{ secrets.FRED_API_KEY }}"' >> Config.toml
          cat Config.toml
          pwd Config.toml
    - name: Build
      working-directory: api
      run: cargo build --release
    - name: Run API for one minute
      working-directory: api
      run: timeout 1m ./target/release/bred-api || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
